version: 2.1

orbs:
  # Note: We are using an older version of hello-build, whereas module A uses the latest
  back-dir-hello-build: circleci/hello-build@0.0.13

jobs:
  back-dir-build:
    docker:
      - image: alpine
    steps:
      - common-say-hello:
          to: B
      - run: echo 'Hello, from module B! :3'

  back-dir-postrun:
    docker:
      - image: alpine
    steps:
      - run: echo 'Another job for B! :3'

workflows:
  back-dir-workflow-x:
    jobs:
      - common-pre
      - back-dir-build:
          requires:
            - common-pre
      - back-dir-postrun:
          requires:
            - back-dir-build
  back-dir-workflow-y:
    jobs:
      - back-dir-hello-build/hello-build